apiVersion: octavia.openstack.org/v1beta1
kind: Octavia
metadata:
  name: octavia
spec:
  databaseInstance: openstack
  databaseUser: octavia
  serviceUser: octavia
  rabbitMqClusterName: rabbitmq
  secret: osp-secret
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  customServiceConfig: |
    [DEFAULT]
    debug = true
  octaviaHousekeeping:
    databaseInstance: openstack
    databaseUser: octavia
    serviceUser: octavia
    serviceAccount: octavia
    role: housekeeping
    certssecret: todo
    secret: osp-secret
    preserveJobs: false
    customServiceConfig: |
      [DEFAULT]
      debug = true
  octaviaHealthManager:
    databaseInstance: openstack
    databaseUser: octavia
    serviceUser: octavia
    serviceAccount: octavia
    role: healthmanager
    certssecret: todo
    secret: osp-secret
    preserveJobs: false
    customServiceConfig: |
      [DEFAULT]
      debug = true
  octaviaWorker:
    databaseInstance: openstack
    databaseUser: octavia
    serviceUser: octavia
    serviceAccount: octavia
    role: worker
    certssecret: todo
    secret: osp-secret
    preserveJobs: false
    customServiceConfig: |
      [DEFAULT]
      debug = true
  octaviaAPI:
    databaseInstance: openstack
    databaseUser: octavia
    serviceUser: octavia
    serviceAccount: octavia
    secret: osp-secret
    debug:
      dbSync: false
      service: false
    preserveJobs: false
    customServiceConfig: |
      [DEFAULT]
      debug = true
